{% set version = "2.0.0dev107" %}

package:
  name: botocore
  version: {{ version }}

source:
  git_url: https://github.com/boto/botocore.git
  git_rev: 35e1ed057cae6f16e0ca0d2865ca6c0ec575a5cc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jmespath >=0.7.1,<1.0.0
    - python-dateutil >=2.1,<3.0.0
    - urllib3 >=1.25.4,<1.27

test:
  imports:
    - botocore
    - botocore.docs
    - botocore.retries
    - botocore.vendored
    - botocore.vendored.requests
    - botocore.vendored.requests.packages
    - botocore.vendored.requests.packages.urllib3

about:
  home: http://aws.amazon.com/sdk-for-python/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_url: http://aws.amazon.com/apache2.0/
  license_family: Apache
  summary: Low-level, data-driven core of boto 3.
  description: |
    Provides the core functionality of Boto3, the AWS SDK for Python
  dev_url: https://github.com/boto/botocore
  doc_url: https://botocore.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - manics
